// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import {
  DestinyInventoryItemDefinition,
  DestinyPlugSetDefinition,
} from 'bungie-api-ts/destiny2'

export const ETERNAL_BLAZON_DEF: DestinyInventoryItemDefinition = {
  displayProperties: {
    description: '',
    name: 'Eternal Blazon',
    icon: '/common/destiny2_content/icons/c8b7a3b8b1715aca7a56e68382cf9951.jpg',
    hasIcon: true,
  },
  tooltipNotifications: [],
  collectibleHash: 2144945645,
  iconWatermark:
    '/common/destiny2_content/icons/5ac4a1d48a5221993a41a5bb524eda1b.png',
  iconWatermarkShelved:
    '/common/destiny2_content/icons/e197b731c11556b17664b90a87dd0c11.png',
  secondaryIcon:
    '/common/destiny2_content/icons/d7596444c338aa5339234cd017810946.png',
  backgroundColor: { colorHash: 0, red: 0, green: 0, blue: 0, alpha: 0 },
  screenshot: '/common/destiny2_content/screenshots/3514096004.jpg',
  itemTypeDisplayName: 'Scout Rifle',
  flavorText:
    '"But this eternal blazon must not be to ears of flesh and blood."',
  uiItemDisplayStyle: '',
  itemTypeAndTierDisplayName: 'Legendary Scout Rifle',
  displaySource:
    'Random Perks: This item cannot be reacquired from Collections.',
  action: {
    verbName: 'Dismantle',
    verbDescription: '',
    isPositive: false,
    requiredCooldownSeconds: 0,
    requiredItems: [],
    progressionRewards: [],
    actionTypeLabel: 'shard',
    rewardSheetHash: 0,
    rewardItemHash: 0,
    rewardSiteHash: 0,
    requiredCooldownHash: 0,
    deleteOnAction: true,
    consumeEntireStack: false,
    useOnAcquire: false,
  },
  inventory: {
    maxStackSize: 1,
    bucketTypeHash: 2465295065,
    recoveryBucketTypeHash: 215593132,
    tierTypeHash: 4008398120,
    isInstanceItem: true,
    nonTransferrableOriginal: false,
    tierTypeName: 'Legendary',
    tierType: 5,
    expirationTooltip: '',
    expiredInActivityMessage: '',
    expiredInOrbitMessage: '',
    suppressExpirationWhenObjectivesComplete: true,
  },
  stats: {
    disablePrimaryStatDisplay: false,
    statGroupHash: 2453149525,
    stats: {
      '155624089': {
        statHash: 155624089,
        value: 34,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '943549884': {
        statHash: 943549884,
        value: 62,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1240592695': {
        statHash: 1240592695,
        value: 33,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1345609583': {
        statHash: 1345609583,
        value: 67,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1480404414': {
        statHash: 1480404414,
        value: 0,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1885944937': {
        statHash: 1885944937,
        value: 0,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1931675084': {
        statHash: 1931675084,
        value: 46,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1935470627': {
        statHash: 1935470627,
        value: 0,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '2714457168': {
        statHash: 2714457168,
        value: 10,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '2715839340': {
        statHash: 2715839340,
        value: 52,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '3555269338': {
        statHash: 3555269338,
        value: 20,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '3871231066': {
        statHash: 3871231066,
        value: 16,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '4043523819': {
        statHash: 4043523819,
        value: 60,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '4188031367': {
        statHash: 4188031367,
        value: 57,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '4284893193': {
        statHash: 4284893193,
        value: 200,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
    },
    hasDisplayableStats: true,
    primaryBaseStatHash: 1480404414,
  },
  equippingBlock: {
    uniqueLabelHash: 0,
    equipmentSlotTypeHash: 2465295065,
    attributes: 0,
    equippingSoundHash: 0,
    hornSoundHash: 0,
    ammoType: 1,
    displayStrings: [''],
  },
  translationBlock: {
    weaponPatternHash: 1243855363,
    defaultDyes: [
      { channelHash: 1667433279, dyeHash: 2963294054 },
      { channelHash: 1667433278, dyeHash: 2963294055 },
      { channelHash: 1667433277, dyeHash: 2963294052 },
    ],
    lockedDyes: [],
    customDyes: [],
    arrangements: [{ classHash: 0, artArrangementHash: 1927800278 }],
    hasGeometry: true,
  },
  preview: {
    screenStyle: 'screen_style_sockets',
    previewVendorHash: 0,
    previewActionString: '',
  },
  quality: {
    itemLevels: [],
    qualityLevel: 0,
    infusionCategoryName: '2806069436',
    infusionCategoryHash: 2806069436,
    infusionCategoryHashes: [2806069436],
    progressionLevelRequirementHash: 3157915980,
    currentVersion: 0,
    versions: [{ powerCapHash: 2759499571 }],
    displayVersionWatermarkIcons: [
      '/common/destiny2_content/icons/5ac4a1d48a5221993a41a5bb524eda1b.png',
    ],
  },
  acquireRewardSiteHash: 0,
  acquireUnlockHash: 0,
  sockets: {
    detail: 'Details',
    socketEntries: [
      {
        socketTypeHash: 3956125808,
        singleInitialItemHash: 1458010786,
        reusablePlugItems: [],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 6,
        reusablePlugSetHash: 18,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 1283453667,
        singleInitialItemHash: 1409978308,
        reusablePlugItems: [{ plugItemHash: 1409978308 }],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 229394633,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 3815406785,
        singleInitialItemHash: 1087426260,
        reusablePlugItems: [{ plugItemHash: 1087426260 }],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 811071122,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2614797986,
        singleInitialItemHash: 4267945040,
        reusablePlugItems: [{ plugItemHash: 4267945040 }],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 2528073885,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2614797986,
        singleInitialItemHash: 2846385770,
        reusablePlugItems: [{ plugItemHash: 2846385770 }],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 961755571,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 1288200359,
        singleInitialItemHash: 4248210736,
        reusablePlugItems: [
          { plugItemHash: 195075337 },
          { plugItemHash: 195075336 },
          { plugItemHash: 195075339 },
          { plugItemHash: 4248210736 },
        ],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 7,
        reusablePlugSetHash: 236342179,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2993594586,
        singleInitialItemHash: 2323986101,
        reusablePlugItems: [
          { plugItemHash: 4003264426 },
          { plugItemHash: 299264772 },
          { plugItemHash: 4278960718 },
          { plugItemHash: 634781242 },
          { plugItemHash: 1225726778 },
          { plugItemHash: 1525622117 },
          { plugItemHash: 1710791394 },
          { plugItemHash: 3789184904 },
          { plugItemHash: 3018373291 },
        ],
        preventInitializationOnVendorPurchase: true,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 7,
        reusablePlugSetHash: 2993594586,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2218962841,
        singleInitialItemHash: 4283235143,
        reusablePlugItems: [
          { plugItemHash: 1590375901 },
          { plugItemHash: 1590375902 },
          { plugItemHash: 1590375903 },
          { plugItemHash: 1590375896 },
          { plugItemHash: 1590375897 },
          { plugItemHash: 1590375898 },
          { plugItemHash: 1590375899 },
          { plugItemHash: 1590375892 },
          { plugItemHash: 1590375893 },
          { plugItemHash: 384158423 },
          { plugItemHash: 150943607 },
          { plugItemHash: 150943604 },
          { plugItemHash: 150943605 },
          { plugItemHash: 150943602 },
          { plugItemHash: 150943603 },
          { plugItemHash: 150943600 },
          { plugItemHash: 150943601 },
          { plugItemHash: 150943614 },
          { plugItemHash: 150943615 },
          { plugItemHash: 2697220197 },
          { plugItemHash: 518224747 },
          { plugItemHash: 518224744 },
          { plugItemHash: 518224745 },
          { plugItemHash: 518224750 },
          { plugItemHash: 518224751 },
          { plugItemHash: 518224748 },
          { plugItemHash: 518224749 },
          { plugItemHash: 518224738 },
          { plugItemHash: 518224739 },
          { plugItemHash: 186337601 },
          { plugItemHash: 1486919755 },
          { plugItemHash: 1486919752 },
          { plugItemHash: 1486919753 },
          { plugItemHash: 1486919758 },
          { plugItemHash: 1486919759 },
          { plugItemHash: 1486919756 },
          { plugItemHash: 1486919757 },
          { plugItemHash: 1486919746 },
          { plugItemHash: 1486919747 },
          { plugItemHash: 3486498337 },
          { plugItemHash: 4283235143 },
          { plugItemHash: 4283235140 },
          { plugItemHash: 4283235141 },
          { plugItemHash: 4283235138 },
          { plugItemHash: 4283235139 },
          { plugItemHash: 4283235136 },
          { plugItemHash: 4283235137 },
          { plugItemHash: 4283235150 },
          { plugItemHash: 4283235151 },
          { plugItemHash: 758092021 },
          { plugItemHash: 3928770367 },
          { plugItemHash: 3928770364 },
          { plugItemHash: 3928770365 },
          { plugItemHash: 3928770362 },
          { plugItemHash: 3928770363 },
          { plugItemHash: 3928770360 },
          { plugItemHash: 3928770361 },
          { plugItemHash: 3928770358 },
          { plugItemHash: 3928770359 },
          { plugItemHash: 3803457565 },
          { plugItemHash: 4105787909 },
          { plugItemHash: 4105787910 },
          { plugItemHash: 4105787911 },
          { plugItemHash: 4105787904 },
          { plugItemHash: 4105787905 },
          { plugItemHash: 4105787906 },
          { plugItemHash: 4105787907 },
          { plugItemHash: 4105787916 },
          { plugItemHash: 4105787917 },
          { plugItemHash: 1154004463 },
          { plugItemHash: 3353797898 },
          { plugItemHash: 3353797897 },
          { plugItemHash: 3353797896 },
          { plugItemHash: 3353797903 },
          { plugItemHash: 3353797902 },
          { plugItemHash: 3353797901 },
          { plugItemHash: 3353797900 },
          { plugItemHash: 3353797891 },
          { plugItemHash: 3353797890 },
          { plugItemHash: 3128594062 },
          { plugItemHash: 2203506848 },
          { plugItemHash: 2203506851 },
          { plugItemHash: 2203506850 },
          { plugItemHash: 2203506853 },
          { plugItemHash: 2203506852 },
          { plugItemHash: 2203506855 },
          { plugItemHash: 2203506854 },
          { plugItemHash: 2203506857 },
          { plugItemHash: 2203506856 },
          { plugItemHash: 1639384016 },
          { plugItemHash: 892374263 },
          { plugItemHash: 892374260 },
          { plugItemHash: 892374261 },
          { plugItemHash: 892374258 },
          { plugItemHash: 892374259 },
          { plugItemHash: 892374256 },
          { plugItemHash: 892374257 },
          { plugItemHash: 892374270 },
          { plugItemHash: 892374271 },
          { plugItemHash: 2993547493 },
          { plugItemHash: 3673787993 },
          { plugItemHash: 3673787994 },
          { plugItemHash: 3673787995 },
          { plugItemHash: 3673787996 },
          { plugItemHash: 3673787997 },
          { plugItemHash: 3673787998 },
          { plugItemHash: 3673787999 },
          { plugItemHash: 3673787984 },
          { plugItemHash: 3673787985 },
          { plugItemHash: 266016299 },
        ],
        preventInitializationOnVendorPurchase: true,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 3,
        reusablePlugSetHash: 2326575037,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 0,
        singleInitialItemHash: 0,
        reusablePlugItems: [],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 1,
        overridesUiAppearance: false,
        defaultVisible: false,
      },
      {
        socketTypeHash: 1282012138,
        singleInitialItemHash: 905869860,
        reusablePlugItems: [],
        preventInitializationOnVendorPurchase: true,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 6,
        reusablePlugSetHash: 5,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
    ],
    intrinsicSockets: [
      {
        plugItemHash: 3690882495,
        socketTypeHash: 3526234181,
        defaultVisible: true,
      },
    ],
    socketCategories: [
      { socketCategoryHash: 3956125808, socketIndexes: [0] },
      { socketCategoryHash: 4241085061, socketIndexes: [1, 2, 3, 4, 9] },
      { socketCategoryHash: 2048875504, socketIndexes: [5] },
      { socketCategoryHash: 2685412949, socketIndexes: [6, 7] },
    ],
  },
  talentGrid: {
    talentGridHash: 521135891,
    itemDetailString: 'Details',
    hudDamageType: 1,
  },
  investmentStats: [
    { statTypeHash: 1480404414, value: 0, isConditionallyActive: false },
    { statTypeHash: 1935470627, value: 0, isConditionallyActive: false },
    { statTypeHash: 1885944937, value: 0, isConditionallyActive: false },
    { statTypeHash: 3555269338, value: 20, isConditionallyActive: false },
    { statTypeHash: 4284893193, value: 80, isConditionallyActive: false },
    { statTypeHash: 4043523819, value: 20, isConditionallyActive: false },
    { statTypeHash: 1240592695, value: 33, isConditionallyActive: false },
    { statTypeHash: 155624089, value: 34, isConditionallyActive: false },
    { statTypeHash: 3871231066, value: 58, isConditionallyActive: false },
    { statTypeHash: 4188031367, value: 57, isConditionallyActive: false },
    { statTypeHash: 1931675084, value: 46, isConditionallyActive: false },
    { statTypeHash: 943549884, value: 62, isConditionallyActive: false },
    { statTypeHash: 1345609583, value: 67, isConditionallyActive: false },
    { statTypeHash: 2715839340, value: 52, isConditionallyActive: false },
    { statTypeHash: 2714457168, value: 10, isConditionallyActive: false },
  ],
  perks: [
    { requirementDisplayString: '', perkHash: 3435464613, perkVisibility: 0 },
  ],
  loreHash: 3514096004,
  summaryItemHash: 3520001075,
  allowActions: true,
  doesPostmasterPullHaveSideEffects: false,
  nonTransferrable: false,
  itemCategoryHashes: [3, 1, 8],
  specialItemType: 0,
  itemType: 3,
  itemSubType: 14,
  classType: 3,
  breakerType: 0,
  equippable: true,
  damageTypeHashes: [2303181850],
  damageTypes: [2],
  defaultDamageType: 2,
  defaultDamageTypeHash: 2303181850,
  isWrapper: false,
  traitIds: ['faction.vanguard', 'foundry.omolon', 'item.weapon.scout_rifle'],
  traitHashes: [3359893241, 192828432, 12026609],
  hash: 3514096004,
  index: 10523,
  redacted: false,
  blacklisted: false,
}
export const TIMELINES_VERTEX_DEF: DestinyInventoryItemDefinition = {
  displayProperties: {
    description: '',
    name: "Timelines' Vertex",
    icon: '/common/destiny2_content/icons/397159323a6b39ae40f2631df9b2b9ff.jpg',
    hasIcon: true,
  },
  tooltipNotifications: [],
  collectibleHash: 1882909875,
  iconWatermark:
    '/common/destiny2_content/icons/b12630659223b53634e9f97c0a0a8305.png',
  iconWatermarkShelved:
    '/common/destiny2_content/icons/e27a4f39c1bb8c6f89613648afaa3e9f.png',
  secondaryIcon:
    '/common/destiny2_content/icons/d7596444c338aa5339234cd017810946.png',
  backgroundColor: {
    colorHash: 0,
    red: 255,
    green: 255,
    blue: 255,
    alpha: 255,
  },
  screenshot: '/common/destiny2_content/screenshots/3055192515.jpg',
  itemTypeDisplayName: 'Fusion Rifle',
  flavorText: '"I give you this, to be sure that we meet again." —Lakshmi-2',
  uiItemDisplayStyle: '',
  itemTypeAndTierDisplayName: 'Legendary Fusion Rifle',
  displaySource:
    'Random Perks: This item cannot be reacquired from Collections.',
  action: {
    verbName: 'Dismantle',
    verbDescription: '',
    isPositive: false,
    requiredCooldownSeconds: 0,
    requiredItems: [],
    progressionRewards: [],
    actionTypeLabel: 'shard',
    rewardSheetHash: 0,
    rewardItemHash: 0,
    rewardSiteHash: 0,
    requiredCooldownHash: 0,
    deleteOnAction: true,
    consumeEntireStack: false,
    useOnAcquire: false,
  },
  inventory: {
    maxStackSize: 1,
    bucketTypeHash: 2465295065,
    recoveryBucketTypeHash: 215593132,
    tierTypeHash: 4008398120,
    isInstanceItem: true,
    nonTransferrableOriginal: false,
    tierTypeName: 'Legendary',
    tierType: 5,
    expirationTooltip: '',
    expiredInActivityMessage: '',
    expiredInOrbitMessage: '',
    suppressExpirationWhenObjectivesComplete: true,
  },
  stats: {
    disablePrimaryStatDisplay: false,
    statGroupHash: 3050455863,
    stats: {
      '155624089': {
        statHash: 155624089,
        value: 40,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '943549884': {
        statHash: 943549884,
        value: 35,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1240592695': {
        statHash: 1240592695,
        value: 35,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1345609583': {
        statHash: 1345609583,
        value: 60,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1480404414': {
        statHash: 1480404414,
        value: 0,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1885944937': {
        statHash: 1885944937,
        value: 0,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1931675084': {
        statHash: 1931675084,
        value: 50,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '1935470627': {
        statHash: 1935470627,
        value: 0,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '2714457168': {
        statHash: 2714457168,
        value: 4,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '2715839340': {
        statHash: 2715839340,
        value: 60,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '2961396640': {
        statHash: 2961396640,
        value: 660,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '3555269338': {
        statHash: 3555269338,
        value: 15,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '3871231066': {
        statHash: 3871231066,
        value: 6,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '4043523819': {
        statHash: 4043523819,
        value: 70,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
      '4188031367': {
        statHash: 4188031367,
        value: 40,
        minimum: 0,
        maximum: 0,
        displayMaximum: 100,
      },
    },
    hasDisplayableStats: true,
    primaryBaseStatHash: 1480404414,
  },
  equippingBlock: {
    uniqueLabelHash: 0,
    equipmentSlotTypeHash: 2465295065,
    attributes: 0,
    equippingSoundHash: 0,
    hornSoundHash: 0,
    ammoType: 2,
    displayStrings: [''],
  },
  translationBlock: {
    weaponPatternHash: 3275990723,
    defaultDyes: [
      { channelHash: 1667433279, dyeHash: 56237740 },
      { channelHash: 1667433278, dyeHash: 56237741 },
      { channelHash: 1667433277, dyeHash: 56237742 },
    ],
    lockedDyes: [],
    customDyes: [],
    arrangements: [{ classHash: 0, artArrangementHash: 1006783454 }],
    hasGeometry: true,
  },
  preview: {
    screenStyle: 'screen_style_sockets',
    previewVendorHash: 0,
    previewActionString: '',
  },
  quality: {
    itemLevels: [],
    qualityLevel: 0,
    infusionCategoryName: '2806069436',
    infusionCategoryHash: 2806069436,
    infusionCategoryHashes: [2806069436],
    progressionLevelRequirementHash: 3157915980,
    currentVersion: 0,
    versions: [{ powerCapHash: 2759499571 }],
    displayVersionWatermarkIcons: [
      '/common/destiny2_content/icons/b12630659223b53634e9f97c0a0a8305.png',
    ],
  },
  acquireRewardSiteHash: 0,
  acquireUnlockHash: 0,
  sockets: {
    detail: 'Details',
    socketEntries: [
      {
        socketTypeHash: 3956125808,
        singleInitialItemHash: 1294026524,
        reusablePlugItems: [],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 6,
        reusablePlugSetHash: 1,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 1283453667,
        singleInitialItemHash: 1409978308,
        reusablePlugItems: [
          { plugItemHash: 1409978308 },
          { plugItemHash: 1628165636 },
        ],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 229394633,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 930927103,
        singleInitialItemHash: 2680121939,
        reusablePlugItems: [
          { plugItemHash: 2680121939 },
          { plugItemHash: 689005463 },
        ],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 2515290978,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2614797986,
        singleInitialItemHash: 957782887,
        reusablePlugItems: [{ plugItemHash: 957782887 }],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 3125115605,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2614797986,
        singleInitialItemHash: 957782887,
        reusablePlugItems: [{ plugItemHash: 957782887 }],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 2,
        randomizedPlugSetHash: 1016227003,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 1288200359,
        singleInitialItemHash: 4248210736,
        reusablePlugItems: [
          { plugItemHash: 195075337 },
          { plugItemHash: 195075336 },
          { plugItemHash: 195075339 },
          { plugItemHash: 4248210736 },
        ],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 7,
        reusablePlugSetHash: 236342179,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 3399577066,
        singleInitialItemHash: 2323986101,
        reusablePlugItems: [
          { plugItemHash: 4003264426 },
          { plugItemHash: 299264772 },
          { plugItemHash: 4278960718 },
          { plugItemHash: 634781242 },
          { plugItemHash: 744770875 },
          { plugItemHash: 1225726778 },
          { plugItemHash: 1525622117 },
          { plugItemHash: 1710791394 },
          { plugItemHash: 3789184904 },
          { plugItemHash: 3018373291 },
        ],
        preventInitializationOnVendorPurchase: true,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 7,
        reusablePlugSetHash: 3399577066,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 2218962841,
        singleInitialItemHash: 3353797898,
        reusablePlugItems: [
          { plugItemHash: 1590375901 },
          { plugItemHash: 1590375902 },
          { plugItemHash: 1590375903 },
          { plugItemHash: 1590375896 },
          { plugItemHash: 1590375897 },
          { plugItemHash: 1590375898 },
          { plugItemHash: 1590375899 },
          { plugItemHash: 1590375892 },
          { plugItemHash: 1590375893 },
          { plugItemHash: 384158423 },
          { plugItemHash: 150943607 },
          { plugItemHash: 150943604 },
          { plugItemHash: 150943605 },
          { plugItemHash: 150943602 },
          { plugItemHash: 150943603 },
          { plugItemHash: 150943600 },
          { plugItemHash: 150943601 },
          { plugItemHash: 150943614 },
          { plugItemHash: 150943615 },
          { plugItemHash: 2697220197 },
          { plugItemHash: 518224747 },
          { plugItemHash: 518224744 },
          { plugItemHash: 518224745 },
          { plugItemHash: 518224750 },
          { plugItemHash: 518224751 },
          { plugItemHash: 518224748 },
          { plugItemHash: 518224749 },
          { plugItemHash: 518224738 },
          { plugItemHash: 518224739 },
          { plugItemHash: 186337601 },
          { plugItemHash: 1486919755 },
          { plugItemHash: 1486919752 },
          { plugItemHash: 1486919753 },
          { plugItemHash: 1486919758 },
          { plugItemHash: 1486919759 },
          { plugItemHash: 1486919756 },
          { plugItemHash: 1486919757 },
          { plugItemHash: 1486919746 },
          { plugItemHash: 1486919747 },
          { plugItemHash: 3486498337 },
          { plugItemHash: 4283235143 },
          { plugItemHash: 4283235140 },
          { plugItemHash: 4283235141 },
          { plugItemHash: 4283235138 },
          { plugItemHash: 4283235139 },
          { plugItemHash: 4283235136 },
          { plugItemHash: 4283235137 },
          { plugItemHash: 4283235150 },
          { plugItemHash: 4283235151 },
          { plugItemHash: 758092021 },
          { plugItemHash: 3928770367 },
          { plugItemHash: 3928770364 },
          { plugItemHash: 3928770365 },
          { plugItemHash: 3928770362 },
          { plugItemHash: 3928770363 },
          { plugItemHash: 3928770360 },
          { plugItemHash: 3928770361 },
          { plugItemHash: 3928770358 },
          { plugItemHash: 3928770359 },
          { plugItemHash: 3803457565 },
          { plugItemHash: 4105787909 },
          { plugItemHash: 4105787910 },
          { plugItemHash: 4105787911 },
          { plugItemHash: 4105787904 },
          { plugItemHash: 4105787905 },
          { plugItemHash: 4105787906 },
          { plugItemHash: 4105787907 },
          { plugItemHash: 4105787916 },
          { plugItemHash: 4105787917 },
          { plugItemHash: 1154004463 },
          { plugItemHash: 3353797898 },
          { plugItemHash: 3353797897 },
          { plugItemHash: 3353797896 },
          { plugItemHash: 3353797903 },
          { plugItemHash: 3353797902 },
          { plugItemHash: 3353797901 },
          { plugItemHash: 3353797900 },
          { plugItemHash: 3353797891 },
          { plugItemHash: 3353797890 },
          { plugItemHash: 3128594062 },
          { plugItemHash: 2203506848 },
          { plugItemHash: 2203506851 },
          { plugItemHash: 2203506850 },
          { plugItemHash: 2203506853 },
          { plugItemHash: 2203506852 },
          { plugItemHash: 2203506855 },
          { plugItemHash: 2203506854 },
          { plugItemHash: 2203506857 },
          { plugItemHash: 2203506856 },
          { plugItemHash: 1639384016 },
          { plugItemHash: 892374263 },
          { plugItemHash: 892374260 },
          { plugItemHash: 892374261 },
          { plugItemHash: 892374258 },
          { plugItemHash: 892374259 },
          { plugItemHash: 892374256 },
          { plugItemHash: 892374257 },
          { plugItemHash: 892374270 },
          { plugItemHash: 892374271 },
          { plugItemHash: 2993547493 },
          { plugItemHash: 3673787993 },
          { plugItemHash: 3673787994 },
          { plugItemHash: 3673787995 },
          { plugItemHash: 3673787996 },
          { plugItemHash: 3673787997 },
          { plugItemHash: 3673787998 },
          { plugItemHash: 3673787999 },
          { plugItemHash: 3673787984 },
          { plugItemHash: 3673787985 },
          { plugItemHash: 266016299 },
        ],
        preventInitializationOnVendorPurchase: true,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 3,
        reusablePlugSetHash: 2326575037,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
      {
        socketTypeHash: 0,
        singleInitialItemHash: 0,
        reusablePlugItems: [],
        preventInitializationOnVendorPurchase: false,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 1,
        overridesUiAppearance: false,
        defaultVisible: false,
      },
      {
        socketTypeHash: 1282012138,
        singleInitialItemHash: 905869860,
        reusablePlugItems: [],
        preventInitializationOnVendorPurchase: true,
        preventInitializationWhenVersioning: false,
        hidePerksInItemTooltip: false,
        plugSources: 6,
        reusablePlugSetHash: 5,
        overridesUiAppearance: false,
        defaultVisible: true,
      },
    ],
    intrinsicSockets: [
      {
        plugItemHash: 3690882495,
        socketTypeHash: 3694988647,
        defaultVisible: true,
      },
    ],
    socketCategories: [
      { socketCategoryHash: 3956125808, socketIndexes: [0] },
      { socketCategoryHash: 4241085061, socketIndexes: [1, 2, 3, 4, 9] },
      { socketCategoryHash: 2048875504, socketIndexes: [5] },
      { socketCategoryHash: 2685412949, socketIndexes: [6, 7] },
    ],
  },
  talentGrid: {
    talentGridHash: 521135891,
    itemDetailString: 'Details',
    hudDamageType: 1,
  },
  investmentStats: [
    { statTypeHash: 1480404414, value: 0, isConditionallyActive: false },
    { statTypeHash: 1935470627, value: 0, isConditionallyActive: false },
    { statTypeHash: 1885944937, value: 0, isConditionallyActive: false },
    { statTypeHash: 3555269338, value: 15, isConditionallyActive: false },
    { statTypeHash: 2961396640, value: 60, isConditionallyActive: false },
    { statTypeHash: 4043523819, value: 40, isConditionallyActive: false },
    { statTypeHash: 1240592695, value: 35, isConditionallyActive: false },
    { statTypeHash: 155624089, value: 40, isConditionallyActive: false },
    { statTypeHash: 3871231066, value: 60, isConditionallyActive: false },
    { statTypeHash: 4188031367, value: 40, isConditionallyActive: false },
    { statTypeHash: 1931675084, value: 50, isConditionallyActive: false },
    { statTypeHash: 943549884, value: 35, isConditionallyActive: false },
    { statTypeHash: 1345609583, value: 60, isConditionallyActive: false },
    { statTypeHash: 2715839340, value: 60, isConditionallyActive: false },
    { statTypeHash: 2714457168, value: 4, isConditionallyActive: false },
  ],
  perks: [
    { requirementDisplayString: '', perkHash: 3486450016, perkVisibility: 0 },
  ],
  summaryItemHash: 3520001075,
  allowActions: true,
  doesPostmasterPullHaveSideEffects: false,
  nonTransferrable: false,
  itemCategoryHashes: [3, 1, 9],
  specialItemType: 0,
  itemType: 3,
  itemSubType: 11,
  classType: 3,
  breakerType: 0,
  equippable: true,
  damageTypeHashes: [1847026933],
  damageTypes: [3],
  defaultDamageType: 3,
  defaultDamageTypeHash: 1847026933,
  isWrapper: false,
  traitIds: [
    'faction.future_war_cult',
    'foundry.omolon',
    'item.weapon.fusion_rifle',
  ],
  traitHashes: [1345630660, 192828432, 2891203715],
  hash: 3055192515,
  index: 9638,
  redacted: false,
  blacklisted: false,
}

export const PLUG_SET_DEFS: {
  [key: number]: DestinyPlugSetDefinition
} = {
  [229394633]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 194952923,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 194952922,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 194952921,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1409978309,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1409978308,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1409978311,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1628165637,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1628165636,
      },
    ],
    isFakePlugSet: false,
    hash: 229394633,
    index: 251,
    redacted: false,
    blacklisted: false,
  },
  [811071122]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2420895100,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1431678320,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1087426260,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1968497646,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1561002382,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1885400500,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3230963543,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 679225683,
      },
    ],
    isFakePlugSet: false,
    hash: 811071122,
    index: 233,
    redacted: false,
    blacklisted: false,
  },
  [2528073885]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4267945040,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2450788523,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3643424744,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3161816588,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 247725512,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 706527188,
      },
    ],
    isFakePlugSet: false,
    hash: 2528073885,
    index: 909,
    redacted: false,
    blacklisted: false,
  },
  [961755571]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2846385770,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1015611457,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4049631843,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3108830275,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1683379515,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2726471870,
      },
    ],
    isFakePlugSet: false,
    hash: 961755571,
    index: 910,
    redacted: false,
    blacklisted: false,
  },
  [2326575037]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375901,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375902,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375903,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375896,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375897,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375898,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375899,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375892,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1590375893,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 384158423,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943607,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943604,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943605,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943602,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943603,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943600,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943601,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943614,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 150943615,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2697220197,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224747,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224744,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224745,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224750,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224751,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224748,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224749,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224738,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 518224739,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 186337601,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919755,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919752,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919753,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919758,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919759,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919756,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919757,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919746,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1486919747,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3486498337,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235143,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235140,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235141,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235138,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235139,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235136,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235137,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235150,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4283235151,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 758092021,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770367,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770364,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770365,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770362,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770363,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770360,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770361,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770358,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3928770359,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3803457565,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787909,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787910,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787911,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787904,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787905,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787906,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787907,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787916,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 4105787917,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1154004463,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797898,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797897,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797896,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797903,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797902,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797901,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797900,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797891,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3353797890,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3128594062,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506848,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506851,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506850,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506853,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506852,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506855,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506854,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506857,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2203506856,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1639384016,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374263,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374260,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374261,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374258,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374259,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374256,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374257,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374270,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 892374271,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2993547493,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787993,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787994,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787995,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787996,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787997,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787998,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787999,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787984,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3673787985,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 266016299,
      },
    ],
    isFakePlugSet: false,
    hash: 2326575037,
    index: 241,
    redacted: false,
    blacklisted: false,
  },
  [2515290978]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 689005463,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2680121939,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1483536627,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1687452232,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3868766766,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2969185026,
      },
    ],
    isFakePlugSet: false,
    hash: 2515290978,
    index: 224,
    redacted: false,
    blacklisted: false,
  },
  [3125115605]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 280464955,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1556840489,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3275789089,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 2869569095,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3300816228,
      },
    ],
    isFakePlugSet: false,
    hash: 3125115605,
    index: 692,
    redacted: false,
    blacklisted: false,
  },
  [1016227003]: {
    displayProperties: { description: '', name: '', hasIcon: false },
    reusablePlugItems: [
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 957782887,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1600092898,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3511092054,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 1683379515,
      },
      {
        craftingRequirements: {
          unlockRequirements: [],
          materialRequirementHashes: [],
        },
        weight: 0,
        alternateWeight: 0,
        currentlyCanRoll: true,
        plugItemHash: 3523296417,
      },
    ],
    isFakePlugSet: false,
    hash: 1016227003,
    index: 693,
    redacted: false,
    blacklisted: false,
  },
}
