name: test

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: pnpm install
        
      - name: Run tests
        run: pnpm test
